version: "2.3"
services:
  web:
    image: "kaspernj/rails-development-base-ubuntu-20-04"
    mem_limit: 4G
    ports:
      - "38022:22"
    volumes:
      - "./shared:/shared"
      - "homedev:/home/dev"
  mariadb:
    image: "mariadb:latest"
    environment:
      MARIADB_ROOT_HOST: "%"
      MARIADB_ROOT_PASSWORD: topsecret
      MARIADB_USER: dev
      MARIADB_PASSWORD: secret
    expose:
      - 3306
    mem_limit: 4G
    volumes:
      - mariadb:/var/lib/mysql
  postgres:
    image: "postgres"
    expose:
      - 5432
    environment:
      POSTGRES_USER: "username"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "database-name"
    mem_limit: 4G
    volumes:
      - postgres:/var/lib/postgresql/data
  redis:
    image: "redis"
    expose:
      - 6379
    mem_limit: 2G
    volumes:
      - redis:/var/lib/redis/data
volumes:
  homedev:
  mariadb:
  redis:
  postgres:
