version: "2.3"
services:
  web:
    image: "kaspernj/rails-development-base-ubuntu-20-04"
    depends_on:
      - mariadb
      - postgres
      - redis
    mem_limit: 4G
    networks:
      default:
        ipv4_address: 38.0.0.2
    ports:
      - "38022:22"
    restart: unless-stopped
    volumes:
      - "./shared:/shared"
      - "homedev:/home/dev"
  mariadb:
    image: "mariadb:latest"
    environment:
      MARIADB_DATABASE: "database-name"
      MARIADB_ROOT_HOST: "%"
      MARIADB_ROOT_PASSWORD: topsecret
      MARIADB_USER: dev
      MARIADB_PASSWORD: secret
    expose:
      - 3306
    mem_limit: 4G
    networks:
      default:
        ipv4_address: 38.0.0.3
    restart: unless-stopped
    volumes:
      - mariadb:/var/lib/mysql
  postgres:
    image: "postgres"
    expose:
      - 5432
    environment:
      POSTGRES_USER: "username"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "database-name"
    mem_limit: 4G
    networks:
      default:
        ipv4_address: 38.0.0.4
    restart: unless-stopped
    volumes:
      - postgres:/var/lib/postgresql/data
  redis:
    image: "redis"
    expose:
      - 6379
    mem_limit: 2G
    networks:
      default:
        ipv4_address: 38.0.0.5
    restart: unless-stopped
    volumes:
      - redis:/var/lib/redis/data
networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: 38.0.0.0/16
volumes:
  homedev:
  mariadb:
  redis:
  postgres:
